# Generated by Django 2.2.5 on 2019-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpapplication',
            name='resume_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='course_work',
            field=models.TextField(blank=True, help_text='List any coursework relevant to building projects or working in teams!', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='extracurricular_work',
            field=models.TextField(blank=True, help_text='List and describe up to 3 extracurricular projects or experiences', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='ieee_member_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='personal_link',
            field=models.URLField(blank=True, help_text='Link to personal website, portfolio or Github', null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='teammates',
            field=models.TextField(blank=True, help_text='Hoping to work with other people? Please list their full name, email and major. (eg: John Smith, jsmith@gmail.com, ECE)', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='technical_skills',
            field=models.TextField(blank=True, help_text='List any technical skills you have with a rating from 1 to 5 (eg: Photoshop (5),  AutoCAD (4), Python (3), Excel (1), etc.)', max_length=3000, null=True),
        ),
    ]
