# Generated by Django 2.2.5 on 2019-09-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190909_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpapplication',
            name='title',
        ),
    ]
