# Generated by Django 2.2.5 on 2019-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190909_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='resume_upload',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
