# Generated by Django 2.2.5 on 2019-09-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190909_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpapplication',
            name='department',
            field=models.CharField(choices=[('ece', 'Electrical and Computer Engineering'), ('cse', 'Computer Science and Engineering'), ('mae', 'Mechanical and Aerospace Engineering'), ('be', 'BioEngineering'), ('ne', 'NanoEngineering'), ('se', 'Structural Engineering'), ('cs', 'Cognitive Science'), ('ds', 'Data Science'), ('math', 'Mathematics'), ('bs', 'Biological Sciences'), ('candb', 'Chemistry & Biochemistry'), ('p', 'Physics'), ('bus', 'Business'), ('hum', 'Humanities'), ('oth', 'Other')], default='ece', max_length=100),
        ),
        migrations.AddField(
            model_name='qpapplication',
            name='how_did_you_hear',
            field=models.CharField(choices=[('gbm', 'IEEE GBM'), ('fb', 'Facebook'), ('news', 'Newsletter'), ('fly', 'Flyer'), ('ta', 'Tabling (Engineers on the Green, Library Walk, etc.)'), ('fr', 'Friend in IEEE UC San Diego'), ('pr', 'Previously in IEEE Quarterly Projects'), ('oth', 'Other')], default='gbm', max_length=100),
        ),
        migrations.AddField(
            model_name='qpapplication',
            name='microcontrollers',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=3),
        ),
        migrations.AddField(
            model_name='qpapplication',
            name='programs',
            field=models.CharField(choices=[('qp', 'Quarterly Projects'), ('qp2', 'QP++'), ('b', 'Both')], default='qp', help_text='Which programs would you like to be considered for?', max_length=50),
        ),
        migrations.AddField(
            model_name='qpapplication',
            name='quarter_long_obligation',
            field=models.CharField(choices=[('y', 'Yes')], default='y', max_length=3),
        ),
        migrations.AddField(
            model_name='qpapplication',
            name='year_of_study',
            field=models.CharField(choices=[('fr', 'Freshman'), ('so', 'Sophomore'), ('ju', 'Junior'), ('se', 'Senior'), ('oth', 'Other')], default='fr', max_length=20),
        ),
    ]
