# Generated by Django 2.2.5 on 2019-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190909_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='department',
            field=models.CharField(choices=[('ece', 'Electrical and Computer Engineering'), ('cse', 'Computer Science and Engineering'), ('mae', 'Mechanical and Aerospace Engineering'), ('be', 'BioEngineering'), ('ne', 'NanoEngineering'), ('se', 'Structural Engineering'), ('cs', 'Cognitive Science'), ('ds', 'Data Science'), ('math', 'Mathematics'), ('bs', 'Biological Sciences'), ('candb', 'Chemistry & Biochemistry'), ('p', 'Physics'), ('bus', 'Business'), ('hum', 'Humanities'), ('oth', 'Other')], default='ece', help_text='Select your department', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='how_did_you_hear',
            field=models.CharField(choices=[('gbm', 'IEEE GBM'), ('fb', 'Facebook'), ('news', 'Newsletter'), ('fly', 'Flyer'), ('ta', 'Tabling (Engineers on the Green, Library Walk, etc.)'), ('fr', 'Friend in IEEE UC San Diego'), ('pr', 'Previously in IEEE Quarterly Projects'), ('oth', 'Other')], default='gbm', help_text='How did you hear about Quarterly Projects?', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='microcontrollers',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', help_text='Have you used microcontrollers before (Raspberry Pi, Arduino, STM, etc)?', max_length=3),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='quarter_long_obligation',
            field=models.CharField(choices=[('y', 'Yes')], default='y', help_text='I understand that IEEE Quarterly Projects is a quarter long obligation and not showcasing my project will look negatively on myself and impact my teammates greatly.', max_length=3),
        ),
    ]
