# Generated by Django 2.2.5 on 2019-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20190909_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='quarter_long_obligation',
            field=models.CharField(choices=[('y', 'Yes')], default='n', help_text='I understand that IEEE Quarterly Projects is a quarter long obligation and not showcasing my project will look negatively on myself and impact my teammates greatly.', max_length=3),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='resume_upload',
            field=models.FileField(blank=True, help_text='Please upload your resume in firstname_lastname_CV.pdf format', null=True, upload_to='resumes/'),
        ),
    ]
