# Generated by Django 2.2.5 on 2019-09-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20190909_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='quarter_long_obligation',
            field=models.CharField(choices=[('y', 'Yes')], default='n', help_text='I understand that this is a quarter long obligation and not showcasing my project will negatively on impact my teammates.', max_length=3),
        ),
    ]
