# Generated by Django 2.2.5 on 2019-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20190909_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='rude_team_member',
            field=models.TextField(help_text='You have a team member that is rude to your team members, does little work, and is in general hard to work with. How do you address this?', max_length=3000),
        ),
    ]
