# Generated by Django 2.2.5 on 2019-09-09 21:00

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20190909_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='resume_upload',
            field=models.FileField(blank=True, help_text='Please upload your resume in "firstname_lastname_CV.pdf" format', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='resumes/'),
        ),
    ]
