# Generated by Django 2.2.5 on 2019-09-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_auto_20190909_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='course_work',
            field=models.TextField(help_text='List any coursework relevant to building projects or working in teams!', max_length=1500),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='project_motivation',
            field=models.TextField(help_text='In one to two sentences, what motivates you to be on a project? Why do you want to build a project, and what benefit does project experience bring to you and your teammates?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='teammates',
            field=models.TextField(blank=True, help_text='Hoping to work with other people? Please list their full name, email and major. (eg: John Smith, jsmith@gmail.com, ECE)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='technical_skills',
            field=models.TextField(help_text='List any technical skills you have with a rating from 1 to 5 (eg: Photoshop (5),  AutoCAD (4), Python (3), Excel (1), etc.)', max_length=1000),
        ),
    ]
