# Generated by Django 2.2.5 on 2019-09-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20190909_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='quarter_long_obligation',
            field=models.CharField(choices=[('y', 'Yes')], default='n', help_text='I understand that this is a quarter long obligation and that not showcasing my project will negatively impact my team.', max_length=3),
        ),
    ]
