# Generated by Django 2.2.5 on 2019-09-11 16:39

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_auto_20190911_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='ieee_member_number',
            field=models.CharField(blank=True, help_text='IEEE Member Number (Optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='personal_link',
            field=models.URLField(blank=True, help_text='Link to personal website, portfolio or Github', null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='project_motivation',
            field=models.TextField(help_text='In one to two sentences, what motivates you to be on a project? Why do you want to build a project, and what benefit does project experience bring to you and your teammates?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='resume_upload',
            field=models.FileField(blank=True, help_text='Please upload your resume in "firstname_lastname_CV.pdf" format', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='teammates',
            field=models.TextField(blank=True, help_text='Hoping to work with other people? Please list their full name, email and major. (eg: John Smith, jsmith@gmail.com, ECE)', max_length=1000, null=True),
        ),
    ]
