# Generated by Django 2.2.5 on 2019-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_auto_20190911_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='department',
            field=models.CharField(choices=[('ece', 'Electrical and Computer Engineering'), ('cse', 'Computer Science and Engineering'), ('mae', 'Mechanical and Aerospace Engineering'), ('be', 'BioEngineering'), ('ne', 'NanoEngineering'), ('se', 'Structural Engineering'), ('cs', 'Cognitive Science'), ('ds', 'Data Science'), ('math', 'Mathematics'), ('bs', 'Biological Sciences'), ('candb', 'Chemistry & Biochemistry'), ('p', 'Physics'), ('bus', 'Business'), ('hum', 'Humanities'), ('oth', 'Other')], default='ece', help_text='Select your department *', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='how_did_you_hear',
            field=models.CharField(choices=[('gbm', 'IEEE GBM'), ('fb', 'Facebook'), ('news', 'Newsletter'), ('fly', 'Flyer'), ('ta', 'Tabling (Engineers on the Green, Library Walk, etc.)'), ('fr', 'Friend in IEEE UC San Diego'), ('pr', 'Previously in IEEE Quarterly Projects'), ('oth', 'Other')], default='gbm', help_text='How did you hear about Quarterly Projects? *', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='ieee_member_number',
            field=models.CharField(blank=True, help_text='IEEE Member Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='microcontrollers',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', help_text='Have you used microcontrollers before (Raspberry Pi, Arduino, STM, etc)? *', max_length=3),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='programs',
            field=models.CharField(choices=[('qp', 'Quarterly Projects'), ('qp2', 'QP++')], default='qp', help_text='Which program would you like to be considered for? *', max_length=50),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='quarter_long_obligation',
            field=models.CharField(choices=[('y', 'Yes')], default='n', help_text='I understand that this is a quarter long obligation and that not showcasing my project will negatively impact my team. *', max_length=3),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='year_of_study',
            field=models.CharField(choices=[('fr', 'Freshman'), ('so', 'Sophomore'), ('ju', 'Junior'), ('se', 'Senior'), ('oth', 'Other')], default='fr', help_text='Year of Study *', max_length=20),
        ),
    ]
