# Generated by Django 2.2.5 on 2019-09-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_auto_20190915_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpapplication',
            name='ieee_member_number',
        ),
    ]
