# Generated by Django 2.2.5 on 2019-09-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_auto_20190925_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpapplication',
            options={'ordering': ['-score']},
        ),
    ]
