# Generated by Django 2.2.5 on 2019-09-25 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_qpapplication_num_of_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
