# Generated by Django 2.2.5 on 2019-09-26 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_auto_20190925_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapplication',
            name='num_of_scores',
            field=models.IntegerField(blank=True, help_text='# of scorers', null=True),
        ),
        migrations.AlterField(
            model_name='qpapplication',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
