# Generated by Django 2.2.5 on 2019-10-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_auto_20190926_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpapplication',
            options={'ordering': ['score']},
        ),
    ]
