# Generated by Django 2.2.5 on 2019-10-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0031_auto_20191009_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
