# Generated by Django 2.2.5 on 2019-10-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0033_auto_20191009_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpapplication',
            options={'ordering': ['score'], 'permissions': (('can_score_applicant', 'Can Score Application'),)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('can_create_team', 'Can Create Team'),)},
        ),
    ]
