# Generated by Django 2.2.5 on 2019-10-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_auto_20191009_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpapplication',
            options={'ordering': ['-score'], 'permissions': (('can_score_applicant', 'Can Score Application'),)},
        ),
    ]
