# Generated by Django 2.2.5 on 2019-10-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_auto_20191009_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'permissions': (('can_create_team', 'Can Create Team'),)},
        ),
    ]
