# Generated by Django 2.2.5 on 2019-10-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0036_auto_20191012_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['nickname', 'name'], 'permissions': (('can_create_team', 'Can Create Team'),)},
        ),
    ]
