# Generated by Django 2.2.5 on 2019-10-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
