# Generated by Django 2.2.5 on 2019-10-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20191012_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='confidence',
            field=models.CharField(default=None, help_text='Collect a sentence from each team member stating why you are confident you will succeed in making this project ', max_length=2000),
            preserve_default=False,
        ),
    ]
