# Generated by Django 2.2.5 on 2019-10-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_projectproposal_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='confidence',
            field=models.CharField(help_text='Collect a sentence from each team member stating why you are confident you will succeed in making this project', max_length=2000),
        ),
    ]
