# Generated by Django 2.2.5 on 2019-11-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='report_num',
            field=models.CharField(choices=[('1', 'Week 5'), ('2', 'Week 7')], default='2', help_text='Choose a milestone report', max_length=50),
        ),
    ]
