# Generated by Django 2.2.5 on 2019-11-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20191117_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='projected',
            field=models.CharField(help_text='What do you hope to accomplish in the next 2 weeks?', max_length=2000),
        ),
    ]
