# Generated by Django 2.2.5 on 2020-01-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20191117_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='report_num',
            field=models.CharField(choices=[('1', 'Week 5'), ('2', 'Week 7')], default='1', help_text='Choose a milestone report', max_length=50),
        ),
    ]
